---
title: catheu.tech
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Cyril de Catheu
email: cdecatheu@gmail.com
lang: en
languages:
- en
description: Data engineering, podcasting pearls.
show_excerpts: true
url: http://catheu.tech
sass:
  sass_dir: _sass
plainwhite:
  analytics_id: UA-143787397-1
  name: Cyril de Catheu
  date_format: "%-d %b %Y"
  sitemap: true
  newsletter: https://world.hey.com/cdecatheu
  giscus:
    repo: cyrilou242/cyrilou242.github.io
    repo_id: MDEwOlJlcG9zaXRvcnkxOTY2NDE0NzQ=
    category: Blog comments
    category_id: DIC_kwDOC7iCws4CdhQL
    mapping: og:title
    strict: 1
    theme: preferred_color_scheme
    lang: en
  social_links:
    github: cyrilou242
    linkedIn: in/cyril-de-catheu
  hypemachine:
    account: cyrilou242
    bcol: fef2eb
    tcol: ff4e47
    lcol: ff4e47
t:
  en:
    tagline: Data Engineer
    home:
      name: Home
      url: "/index-en.html"
theme: plainwhite
plugins:
- jekyll-seo-tag
- jekyll-feed
