title: catheu.tech
author: Cyril de Catheu
email: cdecatheu@gmail.com
lang: fr
languages: ["en", "fr"]
description: I write about NLP and machine learning in data intensive contexts. In French.
show_excerpts: true # set to true to show excerpts on the homepage
url: http://catheu.tech


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  disqus_shortname: catheu.tech
  analytics_id: 'UA-143787397-1'
  name: Cyril de Catheu
  date_format: "%-d %b %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: deCatheu
    github:  cyrilou242
    linkedIn: in/cyril-de-catheu
    # rss: feed.xml
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up

t:
  en:
    tagline: "NLP engineer"
    home:
      name: "Home"
      url: "/index-en.html"

  fr:
    tagline: "Ingénieur NLP"
    home:
      name: "Accueil"
      url: "/"

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
  - jekyll-feed