title: catheu.tech
author: Cyril de Catheu
email: cdecatheu@gmail.com
lang: en
languages: ["en"]
description: Data engineering, podcasting pearls.
show_excerpts: true # set to true to show excerpts on the homepage
url: http://catheu.tech


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  disqus_shortname: catheu-tech
  analytics_id: 'UA-143787397-1'
  abtasty_id: '7a023c31c439e5bb4d32811325ee2e1e'
  name: Cyril de Catheu
  date_format: "%-d %b %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: deCatheu
    github:  cyrilou242
    linkedIn: in/cyril-de-catheu

  # see https://hypem.com/badge
  hypemachine:
    account: cyrilou242
    bcol: fef2eb
    tcol: ff4e47
    lcol: ff4e47

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# - about

t:
  en:
    tagline: "Data Engineer"
    home:
      name: "Home"
      url: "/index-en.html"

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
  - jekyll-feed